# -*- coding: utf-8 -*-
"""database-telcom.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16ccNnRz9szPMEPpyThfG8p8FWJLiZYft
"""

import pandas as pd

tc_df=pd.read_csv("telecom_dataset.csv")

print(tc_df)



import pandas as pd
tc1_df = pd.read_csv("telecom_dataset_1.csv")
tc2_df = pd.read_csv("telecom_dataset_2.csv")

print(tc1_df)

combined_df = pd.merge(tc1_df, tc2_df, on="phone number", how="inner")

print(combined_df)

if combined_df.duplicated().any(): print ("Duplicates available")
else: print("Duplicates not available")

import pandas as pd

tc_df=pd.read_csv("telecom_dataset.csv")

missing_values = tc_df.isnull().sum()
print(missing_values)

missing_values_drop = tc_df.dropna(inplace=True)
print("Dropped rows: ",missing_values_drop,"\n")

fill_values  = tc_df.fillna(method='ffill', inplace=True)
print("Filled rows: ",fill_values,"\n")

mean_data = tc_df['total day minutes'].mean()
median_data = tc_df['total day minutes'].median()
standard_deviation = tc_df['total day minutes'].std()
min_data = tc_df['total day minutes'].min()
max_data = tc_df['total day minutes'].max()
quantitiles_data = tc_df['total day minutes'].quantile([0.25, 0.5, 0.75])

print("Mean:",  mean_data)
print("Median:", median_data)
print("Standard Deviation:", standard_deviation)
print("Minimum:", min_data)
print("Maximum:", max_data)
print("Quantiles:", quantitiles_data)

import matplotlib.pyplot as plt

plt.scatter(tc_df['total day calls'], tc_df['Predicted total day calls'])
plt.xlabel('total day calls')
plt.ylabel('Predicted total day calls')
plt.title('Total day calls Vs  Predicted total day calls')
plt.show()

import seaborn as sns

sns.pairplot(tc_df)
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

num_df = tc_df.select_dtypes(include=[np.number])

corr = num_df.corr()

sns.heatmap(corr, annot=True)
plt.show()

